[package]
name = "php-skywalking-agent"
version = "0.1.0"
authors = ["jmjoy <918734043@qq.com>"]
description = ""
edition = "2021"
rust-version = "1.58"
repository = ""
license = "MulanPSL-2.0"
readme = "README.md"
keywords = []
categories = []
publish = false

[dependencies]
